version: '3'
services:
  explicit-proxy:
    image: sameersbn/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro

  reverse-proxy:
    image: nginx:latest
    ports:
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
